
# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g.
# `/bin/fish`. Entries in `shell.args` are passed unmodified as arguments to the
# shell.
#
# Default:
#   - (Linux/BSD/macOS) `$SHELL` or the user's login shell, if `$SHELL` is unset
#   - (Windows) powershell
shell:
 program: 'C:\Windows\system32\wsl.exe'
 args:
   - ~ -d Arch

import:
- ~/dotfiles/.alacritty.yml